trailingComma: none
# Specify the number of spaces per indentation-level.
tabWidth: 2
# Print semicolons at the ends of statements.
semi: true
# Use single quotes instead of double quotes.
singleQuote: true
# Specify the line length that the printer will wrap on.
printWidth: 80
